import type { ExpressionSpecification, StyleSpecification } from 'maplibre-gl'
import type { Theme } from './theme'

// ---- Colour helpers (dark mode is generated by inverting lightness) ----

function parseColor(str: string): [number, number, number, number] | null {
  const s = str.trim()
  const rgba = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i.exec(s)
  if (rgba) {
    return [+rgba[1], +rgba[2], +rgba[3], rgba[4] !== undefined ? +rgba[4] : 1]
  }
  const hex = /^#([0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i.exec(s)
  if (hex) {
    let h = hex[1]
    if (h.length === 3 || h.length === 4) h = h.split('').map((c) => c + c).join('')
    const r = parseInt(h.slice(0, 2), 16)
    const g = parseInt(h.slice(2, 4), 16)
    const b = parseInt(h.slice(4, 6), 16)
    const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1
    return [r, g, b, a]
  }
  return null
}

function rgbToHsl(r: number, g: number, b: number): [number, number, number] {
  r /= 255; g /= 255; b /= 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b)
  const l = (max + min) / 2
  let h = 0, s = 0
  if (max !== min) {
    const d = max - min
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    if (max === r) h = (g - b) / d + (g < b ? 6 : 0)
    else if (max === g) h = (b - r) / d + 2
    else h = (r - g) / d + 4
    h /= 6
  }
  return [h, s, l]
}

function hslToRgb(h: number, s: number, l: number): [number, number, number] {
  if (s === 0) { const v = Math.round(l * 255); return [v, v, v] }
  const hue = (t: number): number => {
    if (t < 0) t += 1
    if (t > 1) t -= 1
    if (t < 1 / 6) return p + (q - p) * 6 * t
    if (t < 1 / 2) return q
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6
    return p
  }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s
  const p = 2 * l - q
  return [Math.round(hue(h + 1 / 3) * 255), Math.round(hue(h) * 255), Math.round(hue(h - 1 / 3) * 255)]
}

/** Invert lightness to darken a colour (hue is kept, saturation is pulled back slightly). */
function darkenColor(str: string): string {
  const c = parseColor(str)
  if (!c) return str
  const [r, g, b, a] = c
  const [h, s, l] = rgbToHsl(r, g, b)
  const nl = Math.min(0.9, Math.max(0.05, 1 - l))
  const [nr, ng, nb] = hslToRgb(h, s * 0.85, nl)
  return `rgba(${nr},${ng},${nb},${a})`
}

/** Recursively transform only the colour strings inside a paint value (string or expression array). */
function transformValue(v: unknown, fn: (s: string) => string): unknown {
  if (typeof v === 'string') return parseColor(v) ? fn(v) : v
  if (Array.isArray(v)) return v.map((x) => transformValue(x, fn))
  return v
}

/** Transform every colour-ish paint property in a style in one pass. */
function recolor(src: StyleSpecification, fn: (s: string) => string): StyleSpecification {
  const style = structuredClone(src) as StyleSpecification
  for (const layer of style.layers) {
    const paint = (layer as { paint?: Record<string, unknown> }).paint
    if (!paint) continue
    for (const key of Object.keys(paint)) {
      if (key.includes('color')) paint[key] = transformValue(paint[key], fn)
    }
  }
  return style
}

export type Basemap = 'osm' | 'clear' | 'nasa' | 'nasa721' | 'blank'

export const BASEMAP_LABELS: Record<Basemap, string> = {
  osm: 'Map',
  clear: 'Cloud-free',
  nasa: 'Satellite',
  nasa721: 'Flood 7-2-1',
  blank: 'Blank',
}

/** Which basemaps are dated NASA imagery, and so respond to the imagery-date control. */
export const IMAGERY_BASEMAPS: Basemap[] = ['nasa', 'nasa721']

// ---- NASA GIBS imagery ----
//
// NASA's Global Imagery Browse Services serve daily global satellite imagery as WMTS, free and
// without an API key. Unlike a normal basemap these tiles are **dated**: you ask for a specific
// day, which is the entire point here — you can look at the actual picture from the day the flood
// was detected, rather than a mosaic averaged over months.
//
// Note the path order. GIBS is WMTS REST — {TileMatrix}/{TileRow}/{TileCol} — so the row (y) comes
// before the column (x). Writing the usual {z}/{x}/{y} silently returns the wrong tiles.
const GIBS = 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best'

const GIBS_LAYERS: Record<string, { layer: string; label: string; attribution: string }> = {
  nasa: {
    layer: 'VIIRS_SNPP_CorrectedReflectance_TrueColor',
    label: 'VIIRS true colour',
    attribution:
      'Imagery: <a href="https://worldview.earthdata.nasa.gov/" target="_blank" rel="noopener">NASA EOSDIS GIBS</a> — VIIRS/Suomi NPP true colour',
  },
  nasa721: {
    // Bands 7-2-1 put water almost black, vegetation vivid green and cloud cyan. It is the standard
    // combination for seeing standing water from optical imagery, and far more legible for flooding
    // than true colour, where wet ground and shadow look alike.
    layer: 'MODIS_Terra_CorrectedReflectance_Bands721',
    label: 'MODIS bands 7-2-1',
    attribution:
      'Imagery: <a href="https://worldview.earthdata.nasa.gov/" target="_blank" rel="noopener">NASA EOSDIS GIBS</a> — MODIS/Terra bands 7-2-1',
  },
}

// ---- Rainfall overlay (NASA GIBS / GPM IMERG) ----
//
// Measured precipitation rate, drawn over whichever basemap is showing rather than replacing it —
// rain means little without the ground under it. This is an *observation*, unlike the Open-Meteo
// forecasts in the panel: it is what the satellites recorded falling on a given day, which is why
// it is worth putting on the same date control as the imagery. Looking at the flood detection date
// shows you the rain that caused what the radar found.
//
// Two things differ from the imagery layers and both matter:
//   - It is PNG with transparency, not JPEG, because most of the tile is "no rain".
//   - The matrix set only goes to level 6, not 9. MapLibre overzooms past that; asking GIBS for
//     level 7 returns nothing.
export const RAIN_LAYER = 'IMERG_Precipitation_Rate'
export const RAIN_MAX_ZOOM = 6

export function rainTileUrl(date: string): string {
  return `${GIBS}/${RAIN_LAYER}/default/${date}/GoogleMapsCompatible_Level6/{z}/{y}/{x}.png`
}

/**
 * Two days back, in UTC. IMERG is assembled with a longer lag than the reflectance imagery — asking
 * for yesterday returns 404 rather than an empty tile, so the default has to clear the lag or the
 * layer silently shows nothing on first switch-on.
 */
export function defaultRainDate(): string {
  const d = new Date()
  d.setUTCDate(d.getUTCDate() - 2)
  return d.toISOString().slice(0, 10)
}

export const RAIN_ATTRIBUTION =
  'Rainfall: <a href="https://worldview.earthdata.nasa.gov/" target="_blank" rel="noopener">NASA GIBS</a> — GPM IMERG'

// ---- Sentinel-2 cloudless ----
//
// Cloud cannot be removed from a given day's image: the sensor never saw the ground, so there is
// nothing underneath to recover. What *can* be done is show a composite built from many passes,
// keeping only the clear pixel from each — which is what EOX's Sentinel-2 cloudless is. The result
// is a permanently clear picture of the ground.
//
// The trade is explicit: it is a mosaic of a whole year, so it shows the landscape, never a
// particular day. It is the right basemap for "what is normally here"; the dated NASA views remain
// the only way to see the flood itself from optical imagery.
const S2_CLOUDLESS = 'https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2020_3857/default/g'

const S2_ATTRIBUTION =
  '<a href="https://s2maps.eu" target="_blank" rel="noopener">Sentinel-2 cloudless 2020</a> by ' +
  '<a href="https://eox.at" target="_blank" rel="noopener">EOX IT Services</a> (CC BY-NC-SA 4.0), ' +
  'from modified Copernicus Sentinel data 2020'

function cloudlessStyle(theme: Theme): StyleSpecification {
  return {
    version: 8,
    glyphs: GLYPHS,
    sources: {
      s2: {
        type: 'raster',
        tiles: [`${S2_CLOUDLESS}/{z}/{y}/{x}.jpg`],
        tileSize: 256,
        maxzoom: 14,
        attribution: S2_ATTRIBUTION,
      },
    },
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: { 'background-color': theme === 'dark' ? '#0b0d10' : '#eef1f4' },
      },
      { id: 's2', type: 'raster', source: 's2' },
    ],
  } as StyleSpecification
}

/** Yesterday, in UTC. GIBS publishes a day's imagery after it is assembled, so today is often empty. */
export function defaultImageryDate(): string {
  const d = new Date()
  d.setUTCDate(d.getUTCDate() - 1)
  return d.toISOString().slice(0, 10)
}

function gibsStyle(key: string, date: string, theme: Theme): StyleSpecification {
  const cfg = GIBS_LAYERS[key]
  return {
    version: 8,
    glyphs: GLYPHS,
    sources: {
      imagery: {
        type: 'raster',
        tiles: [`${GIBS}/${cfg.layer}/default/${date}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`],
        tileSize: 256,
        // GIBS serves this matrix set to level 9; MapLibre overzooms beyond it rather than 404ing.
        maxzoom: 9,
        attribution: cfg.attribution,
      },
    },
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: { 'background-color': theme === 'dark' ? '#0b0d10' : '#eef1f4' },
      },
      { id: 'imagery', type: 'raster', source: 'imagery' },
    ],
  } as StyleSpecification
}

const GLYPHS = 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf'

/** Cache of the raw style, keyed by name. */
const rawCache = new Map<string, StyleSpecification>()
/** Cache of transformed styles keyed by `${base}-${theme}`. Darkening is expensive, so do it once. */
const styleCache = new Map<string, StyleSpecification>()

// ---- English basemap (OpenStreetMap) ----
//
// OpenFreeMap serves the OpenMapTiles schema (which carries name:en / name:latin) from a global
// planet build and needs no API key. Labels are forced to English below, because the raw style
// stacks the Latin and local names together.
const LIBERTY_URL = 'https://tiles.openfreemap.org/styles/liberty'

const OSM_ATTRIBUTION =
  '<a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> | ' +
  '<a href="https://openfreemap.org/" target="_blank" rel="noopener">OpenFreeMap</a>'

/**
 * Label text in English. Liberty's own labels print the Latin and non-Latin names stacked together;
 * fall through the name fields instead so one language is shown, preferring English.
 * `name` is the last resort — for places with no translation, the local name beats a blank label.
 */
const ENGLISH_LABEL = [
  'coalesce',
  ['get', 'name:en'],
  ['get', 'name_en'],
  ['get', 'name:latin'],
  ['get', 'name'],
] as unknown as ExpressionSpecification

/** Force every place label in a style to English. */
function relabelEnglish(src: StyleSpecification): StyleSpecification {
  const style = structuredClone(src) as StyleSpecification
  for (const layer of style.layers) {
    const layout = (layer as { layout?: Record<string, unknown> }).layout
    const field = layout?.['text-field']
    if (!field) continue
    // Road shields and the like read `ref`, not a name — leave those alone.
    if (!JSON.stringify(field).includes('name')) continue
    layout!['text-field'] = ENGLISH_LABEL
  }
  return style
}

/** OpenStreetMap basemap with English labels. */
async function libertyStyle(): Promise<StyleSpecification> {
  const hit = rawCache.get('osm')
  if (hit) return hit
  const res = await fetch(LIBERTY_URL)
  if (!res.ok) throw new Error(`Could not load the OpenStreetMap basemap style (HTTP ${res.status})`)
  const style = relabelEnglish((await res.json()) as StyleSpecification)
  // The style ships without attribution, but OpenStreetMap requires it.
  for (const src of Object.values(style.sources)) {
    ;(src as { attribution?: string }).attribution = OSM_ATTRIBUTION
  }
  rawCache.set('osm', style)
  return style
}

/** No basemap. A plain style for looking at the shape of the flooded area on its own. */
function blankStyle(theme: Theme): StyleSpecification {
  return {
    version: 8,
    glyphs: GLYPHS,
    sources: {},
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: { 'background-color': theme === 'dark' ? '#14161a' : '#ffffff' },
      },
    ],
  } as StyleSpecification
}

export async function getBasemapStyle(
  base: Basemap,
  theme: Theme,
  imageryDate?: string,
): Promise<StyleSpecification> {
  if (base === 'blank') return blankStyle(theme)
  if (base === 'clear') return cloudlessStyle(theme)
  // Imagery is dated, so it is never cached by theme alone — a different day is a different map.
  if (base in GIBS_LAYERS) return gibsStyle(base, imageryDate ?? defaultImageryDate(), theme)

  const key = `${base}-${theme}`
  const cached = styleCache.get(key)
  if (cached) return cached

  const src = await libertyStyle()
  // The dark theme is generated by inverting the lightness of the selected style's colours.
  const style = theme === 'dark' ? recolor(src, darkenColor) : src

  styleCache.set(key, style)
  return style
}


// ---- Finding a clear day ----

/**
 * Rough cloud cover of one imagery tile, 0 (clear) to 1 (solid cloud).
 *
 * Cloud looks different in the two products, which is the trap here:
 *
 *   true colour   cloud is white — bright and colourless
 *   bands 7-2-1   cloud is **cyan**, because band 7 (SWIR) is dark over cloud while 2 and 1 are
 *                 bright. Land is green and water almost black.
 *
 * A brightness-and-greyness test alone therefore scores a solid-cloud 7-2-1 tile at 0% — measured:
 * a tile that was 87% cyan cloud came back "perfectly clear". Both signatures are counted, which is
 * safe in each product because true-colour water is dark rather than cyan, and 7-2-1 land is green.
 *
 * A heuristic, not a cloud mask — it only has to rank days against each other. Snow would fool it,
 * which does not arise in lowland Myanmar during monsoon.
 */
export async function tileCloudiness(url: string): Promise<number> {
  const img = new Image()
  img.crossOrigin = 'anonymous'
  const loaded = new Promise<boolean>((resolve) => {
    img.onload = () => resolve(true)
    img.onerror = () => resolve(false)
  })
  img.src = url
  if (!(await loaded)) return 1 // a missing tile is unusable, not clear

  const n = 64 // downsampled: enough to judge, cheap to read back
  const canvas = document.createElement('canvas')
  canvas.width = canvas.height = n
  const ctx = canvas.getContext('2d', { willReadFrequently: true })
  if (!ctx) return 1
  ctx.drawImage(img, 0, 0, n, n)
  let cloud = 0
  let counted = 0
  try {
    const { data } = ctx.getImageData(0, 0, n, n)
    for (let i = 0; i < data.length; i += 4) {
      const r = data[i]
      const g = data[i + 1]
      const b = data[i + 2]
      if (r + g + b === 0) continue // black: outside the swath, never observed
      counted++
      const max = Math.max(r, g, b)
      const min = Math.min(r, g, b)
      const white = max > 165 && max - min < 42
      const cyan = b > 140 && b >= g - 25 && b > r + 20
      if (white || cyan) cloud++
    }
  } catch {
    return 1 // tainted canvas: cannot judge, so do not claim it is clear
  }
  // A tile that is almost entirely no-data tells us nothing; treat it as unusable rather than clear.
  if (counted < n * n * 0.2) return 1
  return counted ? cloud / counted : 1
}

/** The GIBS tile URL for one day, used both by the map and by the clear-day search. */
export function gibsTileUrl(base: Basemap, date: string, z: number, x: number, y: number): string {
  const cfg = GIBS_LAYERS[base]
  if (!cfg) return ''
  return `${GIBS}/${cfg.layer}/default/${date}/GoogleMapsCompatible_Level9/${z}/${y}/${x}.jpg`
}
